### ISSUE TITLE
YouTube Mobile: videos broken

### ISSUE THREAD

**Issue by Vistaus** [loouislow81/performance-x-extension#15]
Your extension really sped up my browsing, thanks for that! :+1: 

But the prevent autoplay feature isn't working on YouTube Mobile (I use the mobile site on my laptop as it's very lightweight) in the sense that it does prevent autoplay, but clicking the play button on videos doesn't do anything. Disabling performance-x solves the issue. Could you please fix this? :)

**Comment by loouislow81** [comment]
> Your extension really sped up my browsing, thanks for that! 
> But the prevent autoplay feature isn't working on YouTube Mobile (I use the mobile site on my laptop as it's very lightweight) in the sense that it does prevent autoplay, but clicking the play button on videos doesn't do anything. Disabling performance-x solves the issue. Could you please fix this? :)

Oh, thank you. I never expected people would change to a mobile screen to watch YouTube on a laptop. I would need to look at this issue.

**Comment by Vistaus** [comment]
Thanks. I don't know why, but it seems to be working now. However, it now doesn't work on YouTube Music (music.youtube.com). I'm using the full desktop site there.

**Comment by loouislow81** [comment]
> Thanks. I don't know why, but it seems to be working now. However, it now doesn't work on YouTube Music (music.youtube.com). I'm using the full desktop site there.
> 
> Edit: never mind, it's not fixed - it seems to be a hit or miss. On YouTube Mobile, that is - on YouTube Music (desktop site) it's 100% broken.

I maybe should disable the `5 secs` video preloading...

**Comment by Vistaus** [comment]
1.0.4 didn't fix it: YouTube Mobile and YouTube Music Desktop are still broken :(

**Comment by Vistaus** [comment]
Or maybe you could offer a blacklist option? That way, I can just add YouTube Mobile and YouTube Music Desktop to the blacklist myself, while still enjoying your extension on all other pages :)
